### ISSUE TITLE
No manifest path.

### ISSUE THREAD

**Issue by Doc-Burns** [free-beer/bh2e#1]
Found your page here, tried to install it, no manifest error. Decided against finishing it or just got busy?

**Comment by free-beer** [comment]
Hi,

Yeah, too many other things came along that needed time and attention. It's funny as someone else was just asking about this on Discord too. It's been a while so I had to dust off the knowledge to get him up and running with it so I'll share with you what I said to him.

Locate your FoundryVTT data directory (you can find it on the Configurations tab on the initial launch dialog). Within that you should find a folder called ``Data`` and inside that a folder called ``system``. Clone the repository into this folder and make sure the directory it clones into is called just ``bh2e`` (no extensions or any other changes). If you then restart Foundry if you have it running it should show up as a system in your list of systems.

There is a good deal of functionality in there. A reasonable first stab at a character sheet that supports dice rolling, including the usage and armour dice. There's no data in the system by default, so you have to create things like class abilities yourself but, once you have, you can drag and drop them onto the character sheet (same goes for equipment). Rolls drop their data into chat in a fashion that's a bit clunky (Foundry documentation is, lets just say, not very good). What's there is there, you can give it a try if you want.

I've (hopefully) attached a screenshot I took of how a sample character sheet looks too, just in case you're interested.

![foundryvtt](https://user-images.githubusercontent.com/1424328/111087216-4a77b300-8518-11eb-98ce-d1746f251902.png)

**Comment by free-beer** [comment]
@Doc-Burns not sure if you're still interested but I've done a little work to tidy things up here. I've set it up so it can be installed from within Foundry using it's manifest file. I've added abilities to creatures and I've also added a bunch of documentation (starting from the repo route on Github). I guess this addresses the issue here so I'm going to close it now.

**Comment by free-beer** [comment]
Closing as the issue has now been addressed.
