### ISSUE TITLE
Foundry v9 compatibility

### ISSUE THREAD

**Issue by dinotheextinct** [free-beer/bh2e#11]
Hey there,
still using your system and really enjoying it. Bh2e is just amazing. 
Now there is a new major version of foundry and I am kinda reluctant to update it, in case this module will not work anymore.

Is there any chance you can have a look at if its compatible?

**Comment by free-beer** [comment]
Hi,

It's on the agenda and I will try and get a look at it towards the end of next week. I've already installed v9 and have given it a quick try to see if I could spot anything obvious (I didn't). I guess I'll have to consider putting together some sort of functional regression document listing things that needs touched upon for each release.

Peter

**Comment by dinotheextinct** [comment]
Great, let me know when you need any help. I will open another feature suggestion to not mix up the issues.

**Comment by free-beer** [comment]
v0.3.1 released so marking this one as closed. If you find any issues in the release please let me know.
