### ISSUE TITLE
Feature request: Randomized Creature HP

### ISSUE THREAD

**Issue by dinotheextinct** [free-beer/bh2e#12]
So right now you need to manually decide for the HP of each monster. According to the rule book its determined by the HD the monster has.
My idea would be that the HP of each monster which is put on the scene is randomly rolled according to its HD. e.g. I put two Goblin Snitches on the scene with 1HD each and their HP will be randomly rolled leading to one having 7 HP while the other got unlucky and has only 1 HP.

I am not  sure how much effort this feature would be, so just let me know if its too much hassle.

Thanks in advance.

**Comment by free-beer** [comment]
This took me a very long time to figure out how to do it but it is implemented for the v0.4.0 release.

**Comment by dinotheextinct** [comment]
~~Hey, just wanted to ask how do I achieve the automatically rolled HP for creatures I put on the scene?~~

Nevermind I found the options in the system settings, amazing feature. Wish there was another way to donate you a coffee except with kofi (Paypal).

**Comment by free-beer** [comment]
Launch your game, click on the game settings option, click on the Configure Settings option, select The Black Hack 2e section and ensure that the Randomized Creature HP option is ticked. After that HP should be randomly generated when added to the scene. I've just checked it and it's working (although you will have to switch the resource bars on for the tokens).

Regards,

Peter

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------
