### ISSUE TITLE
Foundry v9 - Impossible to edit character sheet

### ISSUE THREAD

**Issue by PizzalaFlorian** [free-beer/bh2e#13]
![capture_broken](https://user-images.githubusercontent.com/17024682/147985409-8766e25d-1251-4b39-aa91-3dfb638a0d98.PNG)
Hello, i want to use your work on Foundry v9.238, but i can't edit all the character's sheet. I don't see any cell or button to do that, and the orange tool button doesn't produce any changes. Can you help me ?

Thanks

**Comment by PizzalaFlorian** [comment]
also Spell and Prayer layout are empty and without any button

**Comment by free-beer** [comment]
Can I ask what in particular you cannot edit? There is no button or link to trigger editing - just click into the fields and a cursor will appear (I know they look greyed out but it should work). Also, the Spell and Prayer tabs are empty by default, you have to add spells and prayers to the character for these tabs to show anything. You create the spells/prayers on the Foundry Items Directory tab in the right hand area of the interface and then drag and drop them on to the character sheet.

I have version 9.238 installed locally and this works for me so I suspect that it's not necessarily an issue with the code. Maybe consult the documentation - see the wiki entries [here](https://github.com/free-beer/bh2e/wiki/Introduction), [here](https://github.com/free-beer/bh2e/wiki/The-Character-Sheet) and [here](https://github.com/free-beer/bh2e/wiki/Magic) for more details. Let me know if you're still having trouble and I can possibly dig a little deeper.

**Comment by PizzalaFlorian** [comment]
Thank you very much, I didn't find the wiki the first time and I'm not using your work properly. Everything is fine now. 
I'm really sorry to complain for nothing.
