### ISSUE TITLE
Any way to track gold/coins?

### ISSUE THREAD

**Issue by dinotheextinct** [free-beer/bh2e#14]
Hey there, hope you are still reading this. I noticed there is no way to track actually the amount of coins each character has? I feel this would help greatly within a game mostly aimed at exploring and adventuring for coins.

**Comment by free-beer** [comment]
Yeah, I'm still here 😄 - I'll put this on the list of things to add.

**Comment by free-beer** [comment]
Released v0.3.2 that adds in a coins field (on the front page of the character sheet, next to the damage die fields).
