### ISSUE TITLE
Pressing roll buttons opens new window but doesnt roll

### ISSUE THREAD

**Issue by NoxStripes** [free-beer/bh2e#15]
Yeah like it says, when I press on a roll button on the character sheet it just opens a new Window for the game but doesn't Actually roll the dice. This doesn't seem to be as intended

**Comment by free-beer** [comment]
This generally happens when there's an exception thrown in the Javascript. I'll take a look at it but it will be next week before I get the time to dig into it. Is it a specific button or all buttons?

**Comment by NoxStripes** [comment]
Everything that rolls, whether pure attribute rolls or weapon or even usage rolls for gear.

Also when hovering over the roll buttons it just says https://Gamename.forge-vtt.com/game# at the bottom left of my screen, no idea if thats relevant.

Im using Foundry Version 0.8.9

**Comment by free-beer** [comment]
Okay, it's likely something in the most recent release has broken dice rolling (is my guess at the moment). The link thing I think is fine - these are button links that shouldn't go anywhere so the destination is generally set to '#' in that case.

**Comment by free-beer** [comment]
Okay, I've made sure I've the latest install of Foundry and tried accessing the roll buttons on the character sheet and they are working perfectly for me. I noticed in your feedback that you're on Foundry version 0.8.9 where the latest version is Version 9 - Build 249. I know that things broke quite badly because of some major changes in the transition to version 9 and I had to add a lot of fixes, some of which where specifically relating to dice rolling. That being the case I think your only real choice here is to update your Foundry version. I'll leave this issue open a day or two to give you an opportunity to comment but then I'm going to close it.

**Comment by NoxStripes** [comment]
Hello, it's me again. So, to make a long story short, you were right. I was dreading updating my foundry for the longest time out of fear that would wreck all the games I am currently running on it, but after backing it up and then updating it and annoyingly going through every game to check everything is in order I am finally done with it. 

And it works now. It was literally the fact ive been using an older version.

So since this issue is now closed, the only thing I would like to ask for is a way to instantly not only show whether a roll was a success, but also what exactly was rolled, since Nat 1 and Nat 20 tend to have special effects. Maybe display it as Critical Failure or critical success instead? Just a suggestion :) And a way of tracking gold and how level up changed stats  would also be nice.

**Comment by free-beer** [comment]
Glad to hear this is resolved. So, with regards to your requests...

 1. If you click on the black banner in the chat output from a roll it will expand the roll to show what the total rolled was.
 2. A natural one on an Attack roll will be picked out as a critical hit (there will be a green banner on the message in chat stating that it's a critical hit and if you use the Roll Damage button the damage rolled will be doubled). The BH2e rules don't pick out critical successes in other circumstances and don't mention critical failures/fumbles at all AFAIK so I haven't implemented it on other rolls. I might consider adding some sort of indicator to these rolls at a future point.
 3. Yet, tracking coins is on my radar, it's getting the time to get it in there that's the issue.
