### ISSUE TITLE
Request: Magic to use Attribute

### ISSUE THREAD

**Issue by AtomicBrainBag** [free-beer/bh2e#19]
Hello, 
First off, this system is amazing and my group and I love it.

One thing we enjoy doing is hacking in new classes. Recently, we have been working on a bard class and wanted to make the spell casting use Charisma rather than the standard Wisdom/Intelligence. Unfortunately, this is something we cannot automate in your foundry system due to the hard coded Prayer/Spell options.

Could this be something that is added to allow more flexible addition of non-standard spell types?

Thanks for taking the time to look over this, and I look forward to hearing from you,
Andy

**Comment by free-beer** [comment]
Okay, I'll put a little thought into it and see if I can come up with something. Making no promises and not offering any timelines though.

**Comment by AtomicBrainBag** [comment]
That's amazing! No worries on timelines and such. Just excited to bring some feedback :)

**Comment by free-beer** [comment]
Implemented for the v0.4.0 release.
