### ISSUE TITLE
Rolling from sheet isnt working

### ISSUE THREAD

**Issue by Flintwyrm** [free-beer/bh2e#2]
I keep getting this error when I press any of the orange buttons. I have no modules on.

![Screenshot_1713](https://user-images.githubusercontent.com/60701064/114712899-99bf2800-9cfe-11eb-9d7c-1f8e84c29df8.png)

**Comment by free-beer** [comment]
Yeah, spotted this one last night myself. I have a fix and I'll try and get a version rolled out this evening.

**Comment by free-beer** [comment]
Okay, version 0.2.2 has been released. @Flintwyrm let me know if you're still seeing issues. Closing the issue.
