### ISSUE TITLE
Issue: Player character sheet

### ISSUE THREAD

**Issue by AtomicBrainBag** [free-beer/bh2e#20]
Hey,
Thanks for implementing the spell attributes! Wasn't expecting it so quickly!

Now for the issue. The character sheet information doesn't adjust when resizing the window left and right. It overlaps the attributes and character portrait. Nothing wildly game breaking, but it does limit the scale the window can be.

Massive thanks again, 
Andy

**Comment by free-beer** [comment]
Fixed in v0.4.1.
