### ISSUE TITLE
Spanish translation

### ISSUE THREAD

**Issue by WallaceMcGregor** [free-beer/bh2e#21]
Hi

I've done the Spanish translation but I don't know how to send it to you the es.json 😅

Thanks for your work and the spanish community is wating your Black Sword Hack versión 😊

**Comment by free-beer** [comment]
Quickest way is probably to created a PR containing your es.json file. If you're not comfortable doing that then let me know and we'll make alternative arrangements.

**Comment by WallaceMcGregor** [comment]
Ok, I've tried to do a PR, but I am a noob Github user so I don't know if it is well done.

**Comment by free-beer** [comment]
Okay, just released v0.4.3 that includes the Spanish translations, so I'm closing this one out.
