### ISSUE TITLE
V10 Update?

### ISSUE THREAD

**Issue by dinotheextinct** [free-beer/bh2e#26]
Hey I know its a lot to ask probably, but can we expect an Update to use your system for V10?

**Comment by free-beer** [comment]
Currently on holiday so it will be the week after next at the earliest.

**Comment by free-beer** [comment]
Okay, so I tested the system under v10. It does ask to migrate the system to start with and I accepted that to see what effect it would have. I then ran through a bunch of tests and only picked up a couple of cosmetic issues. I'll look to get a release out by the end of the week but I don't believe there are any serious issues with the code as-is. Are there any specific issues that you've encountered that you want looked at?

**Comment by dinotheextinct** [comment]
Sorry for the late reply, somehow email replies are not working for me.

I didn't try to migrate the game world/system yet, because I was worried for data corruption. I can check it if you say its mostly working, ofc making a backup before hand.

I just read that they changed a lot in terms of data structure for v10.

**Comment by free-beer** [comment]
Well if you open the ``regression_tests.ods`` file in the root of the repository, that's the set of things I ran through and I didn't spot anything obvious. Backup is a good idea. If you spot anything then let me know.

**Comment by free-beer** [comment]
Okay, digging a little deeper there does appear to have been substantial breaking changes to the data structure so I will have to take a little more time to figure out what I need to alter.

**Comment by dinotheextinct** [comment]
Let me know if I can help somehow, sadly I have very limited programming knowledge. But if I can anything else, just let me know.

**Comment by free-beer** [comment]
Okay, I made a release that contains updates for the v10 changes but now that I've tried using it in the Forge environment I'm seeing issues, so I don't recommend installing this yet.

**Comment by free-beer** [comment]
Alright, looking at this again it maybe because the default version on the Forge is 9. I think it might be good to go but I'll have to wait until Forge deploy v10 universal (I tried applying the latest version of 10 they had available but not sure it actually used it).

**Comment by dinotheextinct** [comment]
Ah alright, you are using the hosted variant. Do you think there is risk of data corruption if I try to install the updated module? Otherwise I would test it, because my local installation is already on the newest foundry version and I could give you maybe a little feedback.

**Comment by free-beer** [comment]
I actually test on the local client first and only do the forge check after I've developed a level of confidence in what I have locally first. Foundry's changes for this version, while substantial, are relatively straight forward - they have rejigged the entry point to a data structure but the structure itself remains the same. I can't be certain but I believe their 'migration' is just moving that entry point and the majority of changes I made to the code for this release were related to changing how I access the data structure. That being said I can't offer a guarantee but I've had no issues myself while working with it. I've also been looking a rejigging another system I have and the experience has been pretty much the same for that one too.

**Comment by dinotheextinct** [comment]
How can I try to update my black hack module to 0.5.3?

**Comment by free-beer** [comment]
If you're running the local client then look at the list of systems and you should see an update option in there. There's nothing else that needs to be done as far as I'm aware.

**Comment by dinotheextinct** [comment]
Sadly my local foundry installation doesn't offer an update from blackhack module 0.5.2 upwards when I click on update.

**Comment by free-beer** [comment]
Unfortunately I think there's a typo in the ``system.json`` that I guess will require me to make another release to address it. I'll do it when I have time.

**Comment by free-beer** [comment]
Released v0.5.4 to address the issue.

**Comment by dinotheextinct** [comment]
It seems to work, basic rolling functionality is working too. Will test it more thorougly. Thanks already for all your work!
