### ISSUE TITLE
Allow Level 0 Spells

### ISSUE THREAD

**Issue by WisdomOfWombats** [free-beer/bh2e#32]
There are a number of Hacks based on the Black Hack out there, for some it would be great to have level 0 spells,

**Comment by free-beer** [comment]
Out of interest which hacks require level 0 spells?

**Comment by WisdomOfWombats** [comment]
With level 0 spells, I could use the system more easily for the Black Sword Hack. The spells there have no level.

**Comment by free-beer** [comment]
How about just using [this](https://github.com/free-beer/black-sword-hack).

**Comment by WisdomOfWombats** [comment]
I wasn't aware that even existed. I had only looked at the listings in Foundry. Thanks a lot for pointing that out 👍 Then close this issue, nothing to see here :)

**Comment by free-beer** [comment]
Yeah, I've officially register it with the Foundry people so not sure why it's not appear in the listings. I must have a word with them, especially with the game getting a second edition. Let me know if you hit any issues.
