### ISSUE TITLE
Clicking tabs changes active tab on all open character sheets

### ISSUE THREAD

**Issue by apewall** [free-beer/bh2e#34]
https://user-images.githubusercontent.com/1915182/226460144-b8c56962-d31e-45ca-b293-23c812916eb0.mp4

**Comment by free-beer** [comment]
Hmmm, I seem to recall fixing this a while back. Can I just check that you're using the latest version?

**Comment by apewall** [comment]
The video is using the following versions:
BH2e System: v5.5
FoundryVTT: v10.291

**Comment by free-beer** [comment]
Okay, I'll take a deeper look into it.

**Comment by free-beer** [comment]
Alright, I've merged a fix for this into the repository and it will go out as part of the next release.
