### ISSUE TITLE
Function for roll

### ISSUE THREAD

**Issue by tetshuna** [free-beer/bh2e#37]
Hi, if I wanted to create a function to insert, for example, in the formula for throwing dice, how do I recall the data present in the player's sheet? For example: `/r2d6+@this.level.class `

**Comment by free-beer** [comment]
Not sure if I fully understand the question. If you're looking to see what formula's were used for a roll then look at the output for the roll in the chat. If you click on the roll type bar - this is the black bar at the start of the roll output that will say something like Test: Strength or Attack Roll - then this will expand to show you the formula used for the roll and the result. As for the data specific to the character I'm not sure this is available outside of the context of the character sheet but you would need to consult the Foundry documentation in relation to that. Maybe try somewhere like [here](https://foundryvtt.com/api/) or [here](https://foundryvtt.wiki/en/development/api).

**Comment by tetshuna** [comment]
for what it's worth in the pathfinder1 system it is possible to insert functions in the actors that allow to take data present in a character's sheets. To give an example: if I want to make a sword that does as much damage as the levels of a specific class, I can write: `[[/d (@classes.rogue.level)d6]]`
using this string in the weapon damage field, when the character goes to attack with that sword, if he has thief levels these will become the number of d6s that will be thrown. I would need something similar that could be useful for rolls on tables that involve rolling 2d6 by adding the lowest character's level value.

**Comment by free-beer** [comment]
Okay I see what you're getting at now. Sorry but at this point I have no plan to add functionality like that. I will add that this is an open source system and I'm open to considering any PR to enhance functionality.

**Comment by tetshuna** [comment]
oh, I see, unfortunately I don't know enough about it to be able to work on it myself... I also don't know why it is not possible to insert [[1d6]] in the text spaces present in the actors to allow the roll of the dice directly from there or see the result directly ^^ I think it would be very convenient in certain situations, like for example in the space under the monsters to directly see what their assets are, how they react or something like that...in any case thanks for the enormous work you have done!
