### ISSUE TITLE
[Enhancement] V11 Compatibility

### ISSUE THREAD

**Issue by justinthejaguar** [free-beer/bh2e#38]
Updating the system results in the following as of FVTT V11.315
![Screenshot 2023-11-19 at 3 17 33 PM](https://github.com/free-beer/bh2e/assets/38022481/1a5f207c-0527-4b5a-8ee1-c47f39918ea0)
![Screenshot 2023-11-19 at 3 15 35 PM](https://github.com/free-beer/bh2e/assets/38022481/b415441d-2927-4ee3-b408-fca873b9c396)

**Comment by free-beer** [comment]
I just released v0.6.1 that should hopefully address this issue. Let me know if this is not the case.

**Comment by free-beer** [comment]
With a lack of feedback I'm going to assume this is fixed, so I'm closing it.
