### ISSUE TITLE
System Update?

### ISSUE THREAD

**Issue by corerupt83** [free-beer/bh2e#39]
Any chance of an update to foundry v12?
Many things on the character sheets are broken and it's way out of my skill to fix, i have looked and tried to make sense of it all lol.

Currently the armour tracking buttons are non functional and the usage dice for items are not working also.

**Comment by free-beer** [comment]
I'll see if I can find the time to look into this (no promises). What I will say is that I don't have as much time to look at that these days, plus I don't really get any use out of it personally. For that reason, if I do manage to do the update, it will almost certainly be the last one I do and you should plan accordingly.

**Comment by corerupt83** [comment]
Of course. And thank you for the consideration in updating this module.

**Comment by free-beer** [comment]
Okay, I've just pushed v0.7.0 that addresses as many of the issues as I could find.

**Comment by corerupt83** [comment]
You absolute legend, Thank you so much.
